name: CI/CD Staging Linux

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'  # Specify your .NET version

    - name: Restore dependencies
      run: dotnet restore AlansarHMS.sln

    - name: Build
      run: dotnet build AlansarHMS.sln --no-restore --configuration Release

    - name: Substitute Environment Variables in appsettings.Staging.json
      uses: microsoft/variable-substitution@v1
      with:
        files: src/Alansar/Alansar/appsettings.Staging.json
      env:
        ConnectionStrings.DefaultConnection: ${{ secrets.DB_CONNECTION }}
        Flutterwave.PublicKey: ${{ secrets.FLUTTERWAVE_PUBLICKEY }}
        Flutterwave.SecretKey: ${{ secrets.FLUTTERWAVE_SECRETKEY }}
        Flutterwave.EncryptionKey: ${{ secrets.FLUTTERWAVE_ENCRYPTIONKEY }}

    - name: Verify appsettings.Staging.json
      run: cat src/Alansar/Alansar/appsettings.Staging.json

    - name: Publish
      run: dotnet publish AlansarHMS.sln --no-restore --configuration Release --output src/Alansar/Alansar/bin/Release/net8.0/publish

    - name: Verify publish directory
      run: ls -la src/Alansar/Alansar/bin/Release/net8.0/publish


    # Copy to server
    - name: Deploy to Staging - Copy to Server via SCP
      uses: garygrossgarten/github-action-scp@release
      with:
        local: src/Alansar/Alansar/bin/Release/net8.0/publish/
        concurrency: 10
        remote: ${{ secrets.REMOTE_TARGET_STAGING }}
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASSWORD }}

    # Start service
    - name: Start Alansar Service
      uses: garygrossgarten/github-action-ssh@v0.6.3
      with:
        command: service Alansar restart
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        password: ${{ secrets.REMOTE_PASSWORD }}
